config/routes.rb
W::Application.routes.draw do
  
  root :to => 'welcome#index'
  get "welcome/index"
  get   "/timeline" => "users#timeline", :as => 'timeline'
  get   "/login" => 'sessions#create', :as => 'login'
  post  "/login" => 'sessions#new', :as => 'login'
  get   "/logout" => 'sessions#destroy', :as => 'logout'
  match '/auth/:provider/callback', :to => 'sessions#auth'
  match '/auth/failure', :to => 'sessions#failure'
  
  resources :users , :except => [:index] do
      get 'settings', :on => :collection
      get 'posts' => "posts#index", :on => :member
  end
  
  resources :posts do
      resources :steps , :except => [:index]
  end
  match "/user/confirm/:email/:hash" => 'users#confirm'
  get '/:username' , :to=> 'users#show', :as => 'profile'
  
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :steps, :dependent => :destroy
  belongs_to :user
  validates :title, presence: true, uniqueness: true
  validates :user_id, presence: true
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :authorize, only: [:show]
  def index
    @user = User.find(session[:user_id])
    @posts = @user.posts
    
    respond_to do |format|
      if @post
        format.html #render index.html.erb
      else
        format.html 
      end
    end
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html 
      format.json { render json: @user}
    end
  end

  def create
    params[:post][:user_id]=session[:user_id]
    @post = Post.new(params[:post])
    respond_to do |format|
      if @post.save
        flash[:notice] = "Successfully saved!"
        format.html { redirect_to edit_post_path(@post) } 
      else
        format.html { render 'new' }
      end
    end
  end

  def show
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post
        format.html # show.html.erb
        format.json { render json:@post }
      else
        format.json { render :head => 'not found' }
      end
    end
  end

  def edit
    #params[:post][:user_id]=session[:user_id] || @current_user.id
    @user= User.find(session[:user_id])
    @post = @user.posts.find(params[:id])
    respond_to do |format|
      if @post
        format.html 
        format.json {render json:@post }
      else
        format.html {redirect_to post_url, :notice => "You dont have permission to edit this post." } 
      end
    end
  end

  def update
    params[:post][:user_id]=session[:user_id]
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update_attributes(params[:post])
        flash[:notice] = "Successfully updated!."
        format.html { redirect_to edit_post_path(@post) }
        format.js { render '/layouts/notifier_update' }
      else
        flash[:notice] = "Your cant update post."
        format.html { render action: 'edit'}
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
   
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_edit.html.erb
<div class="form vm2">
<%= form_for(@post,remote: true) do |f| %>

	<div class="field">
		<%= f.label 'Recipe Title' %>
		<%= f.text_field :title,size: 40, :class => 'span5' %>
		<%= f.submit :class => 'btn' %>
	</div>
	
<% end %>
</div>

	

app/views/posts/_new_form.html.erb
<%= form_for(@post) do |f| %>

	<div class="field">
		<%= f.label 'Recipe Title' %>
		<%= f.text_field :title,size: 40, :class => 'span5' %>
		<%= f.submit :class => 'btn' %>
	</div>
	
<% end %>

	

app/views/posts/_post.html.erb
<div class="post vm1">
	<h3 class="post_title"> 
		<%= 
		link_to_if session[:user_id], post.title, edit_post_path(post) do
			link_to post.title, post_path(post) 
		end
		%> 
	</h3>
	<h6 clas="post_info">
		<span class="created_at"> <%= time_ago_in_words post.created_at %> ago</span>
		<% unless session[:user_id] %>
		<span class="author"> <%= link_to post.user.name, user_path(post.user.username.downcase) %> </span>
		<% end %>
		<span class="steps"> Has <%= post.steps.count %> steps</span>
	</h6>
	
	<div class="description"> <%= post.description %> </div>
	<% if session[:user_id] %>
		<div class="actions">
			<%= link_to 'Delete', post_path(post) ,confirm: 'Are you sure?', method: :delete, remote: true %>
		</div>
	<% end %>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/create.js.erb
$('.notification').html("<%=j render 'layouts/notification'%>");
$('.notification').fadeIn();
$("#notificator_close").click(function (){
	$(".notification").fadeOut();
	$("#content").animate( { marginTop:"60px" }, 500);
});

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit a Recipe</h1>

<div id="post_edit">
	<%= render 'edit' %>
</div>
<div class="post_steps">
	<ol id="post_steps">
		<%= render @post.steps %>
	</ol>
</div>
<div id="post_steps_form">
	<%= render 'steps/new_form' %>
</div>

app/views/posts/index.html.erb
<% if @posts %>

	<h1>Your Post</h1>
	<div id="post_list">
		<%= render @posts %>
	</div>
	
<% else %>
	<h3>You Dont have post yet</h3>
<% end %>

app/views/posts/new.html.erb
<h1>Create a new Recipe</h1>

<div id="post_new">
	<%= render 'new_form' %>  
</div>
<div id="post_steps">
  
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h6 clas="post_info">
	<span class="created_at"> <%= time_ago_in_words @post.created_at %> ago</span>
	<span class="author"> <%= link_to @post.user.name, user_path(@post.user.username.downcase) %> </span>
</h6>
<div class="description"></div>
<% if @post.steps.count > 0 %>
<div class="steps vm2">
	<h2>Steps to Follow</h2>
	<ol class="vm1">
		<%= render @post.steps %>
	</ol>
</div>
<% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>